### ISSUE TITLE
New error 

### ISSUE THREAD

**Issue by Klagio** [estevez-dev/ha_client#252]
1213 23:46:25 [Debug] :  [Received] <== id:4, success
1213 23:46:25 [Debug] :  [Received] <== id:5, success
1213 23:46:25 [Debug] :  [Received] <== id:6, success
1213 23:46:25 [Debug] :  [Received] <== id:3, success
1213 23:46:25 [Debug] :  [Received] <== event.state_changed: binary_sensor.ping_gilma_ipad
1213 23:46:25 [Debug] :  Creating Lovelace UI
1213 23:46:25 [Debug] :  --Title: null
1213 23:46:25 [Debug] :  --Views count: 10
1213 23:46:25 [Debug] :  ----view id: 0
1213 23:46:25 [Error] :  NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("action")
1213 23:46:25 [Error] :  #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50)
#1      HomeAssistant._createLovelaceCards.<anonymous closure> (file:///D:/src/hass_client/lib/home_assistant.class.dart:490)
#2      _GrowableList.forEach (dart:core/runtime/libgrowable_array.dart:278)
#3      HomeAssistant._createLovelaceCards (file:///D:/src/hass_client/lib/home_assistant.class.dart:430)
#4      HomeAssistant._createLovelaceCards.<anonymous closure> (file:///D:/src/hass_client/lib/home_assistant.class.dart:443)
#5      _GrowableList.forEach (dart:core/runtime/libgrowable_array.dart:278)
#6      HomeAssistant._createLovelaceCards (file:///D:/src/hass_client/lib/home_assistant.class.dart:430)
#7      HomeAssistant._parseLovelace.<anonymous closure> (file:///D:/src/hass_client/lib/home_assistant.class.dart:420)
#8      _GrowableList.forEach (dart:core/runtime/libgrowable_array.dart:278)
#9      HomeAssistant._parseLovelace (file:///D:/src/hass_client/lib/home_assistant.class.dart:412)
#10     HomeAssistant._createUI (file:///D:/src/hass_client/lib/home_assistant.class.dart:538)
#11     HomeAssistant._getData (file:///D:/src/hass_client/lib/home_assistant.class.dart:174)
<asynchronous suspension>
#12     HomeAssistant.fetch.<anonymous closure> (file:///D:/src/hass_client/lib/home_assistant.class.dart:82)
#13     _rootRunUnary (dart:async/zone.dart:1132)
#14     _CustomZone.runUnary (dart:async/zone.dart:1029)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:129)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642)
#17     Future._propagateToListeners (dart:async/future_impl.dart:671)
#18     Future._propagateToListeners (dart:async/future_impl.dart:569)
#19     Future._completeWithValue (dart:async/future_impl.dart:486)
#20     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:516)
#21     _rootRun (dart:async/zone.dart:1124)
#22     _CustomZone.run (dart:async/zone.dart:1021)
#23     _CustomZone.runGuarded (dart:async/zone.dart:923)
#24     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963)
#25     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#26     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)

1213 23:46:27 [Debug] :  [Received] <== event.state_changed: binary_sensor.ping_max_cube
1213 23:46:28 [Debug] :  [Received] <== event.state_changed: sensor.router_current
1213 23:46:28 [Debug] :  [Received] <== event.state_changed: sensor.router_power
1213 23:46:30 [Debug] :  Use lovelace is true
1213 23:46:31 [Debug] :  [Sending] ==> {"id": 7, "type": "get_states"}
1213 23:46:31 [Debug] :  [Sending] ==> {"id": 8, "type": "lovelace/config"}
1213 23:46:31 [Debug] :  [Sending] ==> {"id": 9, "type": "get_config"}
1213 23:46:31 [Debug] :  [Sending] ==> {"id": 10, "type": "get_services"}
1213 23:46:31 [Debug] :  [Sending] ==> {"id": 11, "type": "auth/current_user"}
1213 23:46:31 [Debug] :  [Received] <== id:7, success
1213 23:46:31 [Debug] :  Parsing 1317 Home Assistant entities
1213 23:46:31 [Debug] :  [Received] <== id:9, success
1213 23:46:31 [Debug] :  [Received] <== id:10, success
1213 23:46:31 [Debug] :  [Received] <== id:11, success
1213 23:46:31 [Debug] :  [Received] <== id:8, success
1213 23:46:31 [Debug] :  [Received] <== event.state_changed: sensor.oven_current
1213 23:46:31 [Debug] :  Creating Lovelace UI
1213 23:46:31 [Debug] :  --Title: null
1213 23:46:31 [Debug] :  --Views count: 10
1213 23:46:31 [Debug] :  ----view id: 0
1213 23:46:31 [Error] :  NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("action")
1213 23:46:31 [Error] :  #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50)
#1      HomeAssistant._createLovelaceCards.<anonymous closure> (file:///D:/src/hass_client/lib/home_assistant.class.dart:490)
#2      _GrowableList.forEach (dart:core/runtime/libgrowable_array.dart:278)
#3      HomeAssistant._createLovelaceCards (file:///D:/src/hass_client/lib/home_assistant.class.dart:430)
#4      HomeAssistant._createLovelaceCards.<anonymous closure> (file:///D:/src/hass_client/lib/home_assistant.class.dart:443)
#5      _GrowableList.forEach (dart:core/runtime/libgrowable_array.dart:278)
#6      HomeAssistant._createLovelaceCards (file:///D:/src/hass_client/lib/home_assistant.class.dart:430)
#7      HomeAssistant._parseLovelace.<anonymous closure> (file:///D:/src/hass_client/lib/home_assistant.class.dart:420)
#8      _GrowableList.forEach (dart:core/runtime/libgrowable_array.dart:278)
#9      HomeAssistant._parseLovelace (file:///D:/src/hass_client/lib/home_assistant.class.dart:412)
#10     HomeAssistant._createUI (file:///D:/src/hass_client/lib/home_assistant.class.dart:538)
#11     HomeAssistant._getData (file:///D:/src/hass_client/lib/home_assistant.class.dart:174)
<asynchronous suspension>
#12     HomeAssistant.fetch.<anonymous closure> (file:///D:/src/hass_client/lib/home_assistant.class.dart:82)
#13     _rootRunUnary (dart:async/zone.dart:1132)
#14     _CustomZone.runUnary (dart:async/zone.dart:1029)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:129)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642)
#17     Future._propagateToListeners (dart:async/future_impl.dart:671)
#18     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:351)
#19     _rootRun (dart:async/zone.dart:1124)
#20     _CustomZone.run (dart:async/zone.dart:1021)
#21     _CustomZone.runGuarded (dart:async/zone.dart:923)
#22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963)
#23     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)

1213 23:46:35 [Debug] :  [Received] <== event.state_changed: sensor.today_main_kwh
1213 23:46:35 [Debug] :  [Received] <== event.state_changed: automation.main_daily_energy
1213 23:46:35 [Debug] :  [Received] <== event.state_changed: automation.sensor_values_to_file
1213 23:46:35 [Debug] :  [Received] <== event.state_changed: binary_sensor.pir_kitchen
1213 23:46:36 [Debug] :  [Received] <== event.state_changed: sensor.load_15m
1213 23:46:36 [Debug] :  [Received] <== event.state_changed: binary_sensor.ping_netatmo_office
1213 23:46:36 [Debug] :  [Received] <== event.state_changed: sensor.memory_free
1213 23:46:36 [Debug] :  [Received] <== event.state_changed: sensor.load_1m
1213 23:46:36 [Debug] :  [Received] <== event.state_changed: sensor.load_5m
1213 23:46:36 [Debug] :  [Received] <== event.state_changed: sensor.asuswrt_upload_speed
1213 23:46:36 [Debug] :  [Received] <== event.state_changed: sensor.asuswrt_download_speed
1213 23:46:37 [Debug] :  [Received] <== event.state_changed: cover.porsche
1213 23:46:37 [Debug] :  [Received] <== event.state_changed: sensor.efergy_802171
1213 23:46:38 [Debug] :  [Received] <== event.state_changed: sensor.router_current
1213 23:46:38 [Debug] :  [Received] <== event.state_changed: sensor.router_voltage
1213 23:46:38 [Debug] :  [Received] <== event.state_changed: sensor.total_router_energy_consumed
1213 23:46:39 [Debug] :  [Received] <== event.state_changed: sensor.qnap3_cpu_usage
1213 23:46:39 [Debug] :  [Received] <== event.state_changed: sensor.qnap3_memory_usage
1213 23:46:39 [Debug] :  [Received] <== event.state_changed: sensor.qnap3_status
1213 23:46:39 [Debug] :  [Received] <== event.state_changed: sensor.qnap3_network_up_eth0
1213 23:46:39 [Debug] :  [Received] <== event.state_changed: sensor.qnap3_network_up_eth1
1213 23:46:41 [Debug] :  [Received] <== event.state_changed: sensor.oven_current
1213 23:46:41 [Debug] :  [Received] <== event.state_changed: binary_sensor.ping_pihole
1213 23:46:42 [Debug] :  [Received] <== event.state_changed: sensor.energy_usage
1213 23:46:42 [Debug] :  [Received] <== event.state_changed: binary_sensor.ping_router_tenda
1213 23:46:45 [Debug] :  [Received] <== event.state_changed: binary_sensor.east_two_line_crossing
1213 23:46:45 [Debug] :  [Received] <== event.state_changed: automation.main_daily_energy
1213 23:46:45 [Debug] :  [Received] <== event.state_changed: automation.sensor_values_to_file
1213 23:46:45 [Debug] :  [Received] <== event.state_changed: sensor.today_main_kwh
1213 23:46:45 [Debug] :  [Received] <== event.state_changed: binary_sensor.ping_gilma_ipad
1213 23:46:48 [Debug] :  [Received] <== event.state_changed: sensor.router_voltage
1213 23:46:51 [Debug] :  [Received] <== event.state_changed: sensor.illumination_kitchen
1213 23:46:51 [Debug] :  [Received] <== event.state_changed: binary_sensor.pir_kitchen
1213 23:46:51 [Debug] :  [Received] <== event.state_changed: automation.motion_kitchen__on_light_new_type
1213 23:46:51 [Debug] :  [Received] <== event.state_changed: sensor.oven_current
1213 23:46:52 [Debug] :  AppLifecycleState.inactive
1213 23:46:53 [Debug] :  [Received] <== event.state_changed: cover.porsche
1213 23:46:53 [Debug] :  AppLifecycleState.paused
1213 23:46:54 [Debug] :  [Received] <== event.state_changed: binary_sensor.ping_netatmo_grandma
1213 23:46:55 [Debug] :  [Received] <== event.state_changed: automation.main_daily_energy
1213 23:46:55 [Debug] :  [Received] <== event.state_changed: sensor.today_main_kwh
1213 23:46:55 [Debug] :  [Received] <== event.state_changed: automation.sensor_values_to_file
1213 23:46:56 [Debug] :  [Received] <== event.state_changed: binary_sensor.ping_efergy
1213 23:46:56 [Debug] :  [Received] <== event.state_changed: sensor.time
1213 23:46:56 [Debug] :  AppLifecycleState.inactive
1213 23:46:56 [Debug] :  AppLifecycleState.resumed
1213 23:46:56 [Debug] :  Use lovelace is true
1213 23:46:56 [Debug] :  [Sending] ==> {"id": 12, "type": "get_states"}
1213 23:46:56 [Debug] :  [Sending] ==> {"id": 13, "type": "lovelace/config"}
1213 23:46:56 [Debug] :  [Sending] ==> {"id": 14, "type": "get_config"}
1213 23:46:56 [Debug] :  [Sending] ==> {"id": 15, "type": "get_services"}
1213 23:46:56 [Debug] :  [Sending] ==> {"id": 16, "type": "auth/current_user"}
1213 23:46:56 [Debug] :  [Received] <== id:12, success
1213 23:46:56 [Debug] :  Parsing 1317 Home Assistant entities
1213 23:46:56 [Debug] :  [Received] <== id:14, success
1213 23:46:56 [Debug] :  [Received] <== id:15, success
1213 23:46:56 [Debug] :  [Received] <== id:16, success
1213 23:46:57 [Debug] :  [Received] <== id:13, success
1213 23:46:57 [Debug] :  [Received] <== event.state_changed: binary_sensor.ping_broadlink_irma_room
1213 23:46:57 [Debug] :  Creating Lovelace UI
1213 23:46:57 [Debug] :  --Title: null
1213 23:46:57 [Debug] :  --Views count: 10
1213 23:46:57 [Debug] :  ----view id: 0
1213 23:46:57 [Error] :  NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("action")
1213 23:46:57 [Error] :  #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50)
#1      HomeAssistant._createLovelaceCards.<anonymous closure> (file:///D:/src/hass_client/lib/home_assistant.class.dart:490)
#2      _GrowableList.forEach (dart:core/runtime/libgrowable_array.dart:278)
#3      HomeAssistant._createLovelaceCards (file:///D:/src/hass_client/lib/home_assistant.class.dart:430)
#4      HomeAssistant._createLovelaceCards.<anonymous closure> (file:///D:/src/hass_client/lib/home_assistant.class.dart:443)
#5      _GrowableList.forEach (dart:core/runtime/libgrowable_array.dart:278)
#6      HomeAssistant._createLovelaceCards (file:///D:/src/hass_client/lib/home_assistant.class.dart:430)
#7      HomeAssistant._parseLovelace.<anonymous closure> (file:///D:/src/hass_client/lib/home_assistant.class.dart:420)
#8      _GrowableList.forEach (dart:core/runtime/libgrowable_array.dart:278)
#9      HomeAssistant._parseLovelace (file:///D:/src/hass_client/lib/home_assistant.class.dart:412)
#10     HomeAssistant._createUI (file:///D:/src/hass_client/lib/home_assistant.class.dart:538)
#11     HomeAssistant._getData (file:///D:/src/hass_client/lib/home_assistant.class.dart:174)
<asynchronous suspension>
#12     HomeAssistant.fetch.<anonymous closure> (file:///D:/src/hass_client/lib/home_assistant.class.dart:82)
#13     _rootRunUnary (dart:async/zone.dart:1132)
#14     _CustomZone.runUnary (dart:async/zone.dart:1029)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:129)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642)
#17     Future._propagateToListeners (dart:async/future_impl.dart:671)
#18     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:351)
#19     _rootRun (dart:async/zone.dart:1124)
#20     _CustomZone.run (dart:async/zone.dart:1021)
#21     _CustomZone.runGuarded (dart:async/zone.dart:923)
#22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963)
#23     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)

1213 23:46:58 [Debug] :  [Received] <== event.state_changed: sensor.router_current
1213 23:46:58 [Debug] :  [Received] <== event.state_changed: sensor.router_power

**Comment by estevez-dev** [comment]
Thanks, will fix
