### ISSUE TITLE
Error code 13?

### ISSUE THREAD

**Issue by konzolec** [estevez-dev/ha_client#266]
For some time now App shows only 5 of 8 cards.

Log is attached
```
0106 20:54:16 [Debug] :  <!!!> Creating new HomeAssistant instance
0106 20:54:16 [Debug] :  AppLifecycleState.inactive
0106 20:54:16 [Debug] :  AppLifecycleState.resumed
0106 20:54:17 [Error] :  Invalid argument(s): 56.0
0106 20:54:17 [Error] :  NoSuchMethodError: The getter 'scrollOffsetCorrection' was called on null.
Receiver: null
Tried calling: scrollOffsetCorrection
0106 20:54:17 [Error] :  NoSuchMethodError: The getter 'visible' was called on null.
Receiver: null
Tried calling: visible
0106 20:54:17 [Debug] :  Use lovelace is true
0106 20:54:17 [Debug] :  Socket connecting...
0106 20:54:17 [Error] :  Invalid argument(s): 56.0
0106 20:54:17 [Error] :  NoSuchMethodError: The getter 'scrollOffsetCorrection' was called on null.
Receiver: null
Tried calling: scrollOffsetCorrection
0106 20:54:17 [Error] :  NoSuchMethodError: The getter 'visible' was called on null.
Receiver: null
Tried calling: visible
0106 20:54:17 [Debug] :  [Sending] ==> auth request
0106 20:54:17 [Debug] :  [Sending] ==> {"id": 1, "type": "subscribe_events", "event_type": "state_changed"}
0106 20:54:17 [Debug] :  [Sending] ==> {"id": 2, "type": "get_states"}
0106 20:54:17 [Debug] :  [Sending] ==> {"id": 3, "type": "lovelace/config"}
0106 20:54:17 [Debug] :  [Sending] ==> {"id": 4, "type": "get_config"}
0106 20:54:17 [Debug] :  [Sending] ==> {"id": 5, "type": "get_services"}
0106 20:54:17 [Debug] :  [Sending] ==> {"id": 6, "type": "auth/current_user"}
0106 20:54:18 [Debug] :  [Received] <== id:1, success
0106 20:54:18 [Debug] :  [Received] <== id:2, success
0106 20:54:18 [Debug] :  Parsing 252 Home Assistant entities
0106 20:54:18 [Debug] :  [Received] <== id:4, success
0106 20:54:18 [Debug] :  [Received] <== id:3, success
0106 20:54:18 [Debug] :  [Received] <== id:5, success
0106 20:54:18 [Debug] :  [Received] <== id:6, success
0106 20:54:18 [Debug] :  Creating Lovelace UI
0106 20:54:18 [Debug] :  --Title: Dom
0106 20:54:18 [Debug] :  --Views count: 8
0106 20:54:18 [Debug] :  ----view id: 0
0106 20:54:18 [Debug] :  ----view id: 1
0106 20:54:18 [Debug] :  ----view id: 2
0106 20:54:18 [Debug] :  ----view id: 3
0106 20:54:18 [Debug] :  ----view id: 4
0106 20:54:18 [Debug] :  ----view id: 5
0106 20:54:18 [Error] :  type 'bool' is not a subtype of type 'String'
0106 20:54:18 [Error] :  #0      HomeAssistant._createLovelaceCards.<anonymous closure>.<anonymous closure> (file:///D:/src/hass_client/lib/home_assistant.class.dart:459)
#1      _GrowableList.forEach (dart:core/runtime/libgrowable_array.dart:278)
#2      HomeAssistant._createLovelaceCards.<anonymous closure> (file:///D:/src/hass_client/lib/home_assistant.class.dart:447)
#3      _GrowableList.forEach (dart:core/runtime/libgrowable_array.dart:278)
#4      HomeAssistant._createLovelaceCards (file:///D:/src/hass_client/lib/home_assistant.class.dart:432)
#5      HomeAssistant._parseLovelace.<anonymous closure> (file:///D:/src/hass_client/lib/home_assistant.class.dart:422)
#6      _GrowableList.forEach (dart:core/runtime/libgrowable_array.dart:278)
#7      HomeAssistant._parseLovelace (file:///D:/src/hass_client/lib/home_assistant.class.dart:414)
#8      HomeAssistant._createUI (file:///D:/src/hass_client/lib/home_assistant.class.dart:507)
#9      HomeAssistant._getData (file:///D:/src/hass_client/lib/home_assistant.class.dart:174)
<asynchronous suspension>
#10     HomeAssistant.fetch.<anonymous closure> (file:///D:/src/hass_client/lib/home_assistant.class.dart:82)
#11     _rootRunUnary (dart:async/zone.dart:1132)
#12     _CustomZone.runUnary (dart:async/zone.dart:1029)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:129)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642)
#15     Future._propagateToListeners (dart:async/future_impl.dart:671)
#16     Future._propagateToListeners (dart:async/future_impl.dart:569)
#17     Future._completeWithValue (dart:async/future_impl.dart:486)
#18     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:516)
#19     _rootRun (dart:async/zone.dart:1124)
#20     _CustomZone.run (dart:async/zone.dart:1021)
#21     _CustomZone.runGuarded (dart:async/zone.dart:923)
#22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963)
#23     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
```

**Comment by estevez-dev** [comment]
You can't use legacy password for authentication any more. Please switch to access token: https://www.vynn.co/ha-client/documentation/#config-auth

**Comment by konzolec** [comment]
I am using access token, login is not the problem.  Just panels are missing.

[https://ibb.co/TP5yC0s](url)
[https://ibb.co/103xrGf](url)

**Comment by konzolec** [comment]
Here you go

https://pastecode.xyz/view/f7409101

Cards 5,6,7 are not shown.  0 1 2 3 4 are shown as can be seen on [Pic1](https://ibb.co/TP5yC0s)

Included also screns from HA [5](https://ibb.co/J230Kb0) [6](https://ibb.co/1ZxFtt6) [7](https://ibb.co/Yp4qM6G)

**Comment by estevez-dev** [comment]
Hey @konzolec . Could you please reupload your config? It leads to 404 now. Thanks.

**Comment by estevez-dev** [comment]
Closing due to inactivity. @konzolec If the issue is still relevant, feel free to reopen or create a new one.
