### ISSUE TITLE
Can't connect to HA with remote access

### ISSUE THREAD

**Issue by Kvasenok** [estevez-dev/ha_client#327]
I can't connect to HA with duckdns. Before the update it used to work through port 443, now I'm getting "There was some error (code: 13)". At the same time I have an iframe_panel with configurator add-on which I can see in the side menu. Web UI also works. 

Logs:
````
0314 17:27:38 [Debug] :  [Received] <== id:222, success
0314 17:27:38 [Debug] :  We actually don`t need the list of servcies for now
0314 17:27:38 [Debug] :  [Received] <== id:223, success
0314 17:27:38 [Error] :  NoSuchMethodError: The method '*' was called on null.
Receiver: null
Tried calling: *()
0314 17:27:38 [Error] :  #0      new Duration. (dart:core/duration.dart:103)
#1      TimerEntity.update (file:///home/estevez/src/ha_client/lib/entity_class/timer_entity.dart:10)
#2      new Entity. (file:///home/estevez/src/ha_client/lib/entity_class/entity.class.dart:119)
#3      new TimerEntity. (file:///home/estevez/src/ha_client/lib/entity_class/timer_entity.dart:4)
#4      EntityCollection._createEntityInstance (file:///home/estevez/src/ha_client/lib/entity_collection.class.dart:37)
#5      EntityCollection.addFromRaw (file:///home/estevez/src/ha_client/lib/entity_collection.class.dart:119)
#6      EntityCollection.parse.<anonymous closure> (file:///home/estevez/src/ha_client/lib/entity_collection.class.dart:24)
#7      _GrowableList.forEach (dart:core/runtime/libgrowable_array.dart:278)
#8      EntityCollection.parse (file:///home/estevez/src/ha_client/lib/entity_collection.class.dart:23)
#9      HomeAssistant._getStates.<anonymous closure> (file:///home/estevez/src/ha_client/lib/home_assistant.class.dart:244)
#10     _rootRunUnary (dart:async/zone.dart:1132)
#11     _CustomZone.runUnary (dart:async/zone.dart:1029)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:126)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639)
#14     Future._propagateToListeners (dart:async/future_impl.dart:668)
#15     Future._completeWithValue (dart:async/future_impl.dart:483)
#16     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513)
#17     _rootRun (dart:async/zone.dart:1124)
#18     _CustomZone.run (dart:async/zone.dart:1021)
#19     _CustomZone.runGuarded (dart:async/zone.dart:923)
#20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)

0314 17:27:40 [Debug] :  Use lovelace is true
0314 17:27:40 [Debug] :  [Sending] ==> {"id": 225, "type": "get_states"}
0314 17:27:40 [Debug] :  [Sending] ==> {"id": 226, "type": "lovelace/config"}
0314 17:27:40 [Debug] :  [Sending] ==> {"id": 227, "type": "get_config"}
0314 17:27:40 [Debug] :  [Sending] ==> {"id": 228, "type": "get_services"}
0314 17:27:40 [Debug] :  [Sending] ==> {"id": 229, "type": "auth/current_user"}
0314 17:27:40 [Debug] :  [Sending] ==> {"id": 230, "type": "get_panels"}
0314 17:27:40 [Debug] :  [Received] <== id:225, success
0314 17:27:40 [Debug] :  Parsing 183 Home Assistant entities
0314 17:27:40 [Debug] :  [Received] <== id:227, success
0314 17:27:40 [Debug] :  [Received] <== id:230, success
0314 17:27:40 [Debug] :  [Received] <== id:226, success
0314 17:27:40 [Debug] :  [Received] <== id:228, success
0314 17:27:40 [Debug] :  We actually don`t need the list of servcies for now
0314 17:27:40 [Debug] :  [Received] <== id:229, success
0314 17:27:40 [Error] :  NoSuchMethodError: The method '*' was called on null.
Receiver: null
Tried calling: *()
0314 17:27:40 [Error] :  #0      new Duration. (dart:core/duration.dart:103)
#1      TimerEntity.update (file:///home/estevez/src/ha_client/lib/entity_class/timer_entity.dart:10)
#2      new Entity. (file:///home/estevez/src/ha_client/lib/entity_class/entity.class.dart:119)
#3      new TimerEntity. (file:///home/estevez/src/ha_client/lib/entity_class/timer_entity.dart:4)
#4      EntityCollection._createEntityInstance (file:///home/estevez/src/ha_client/lib/entity_collection.class.dart:37)
#5      EntityCollection.addFromRaw (file:///home/estevez/src/ha_client/lib/entity_collection.class.dart:119)
#6      EntityCollection.parse.<anonymous closure> (file:///home/estevez/src/ha_client/lib/entity_collection.class.dart:24)
#7      _GrowableList.forEach (dart:core/runtime/libgrowable_array.dart:278)
#8      EntityCollection.parse (file:///home/estevez/src/ha_client/lib/entity_collection.class.dart:23)
#9      HomeAssistant._getStates.<anonymous closure> (file:///home/estevez/src/ha_client/lib/home_assistant.class.dart:244)
#10     _rootRunUnary (dart:async/zone.dart:1132)
#11     _CustomZone.runUnary (dart:async/zone.dart:1029)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:126)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639)
#14     Future._propagateToListeners (dart:async/future_impl.dart:668)
#15     Future._completeWithValue (dart:async/future_impl.dart:483)
#16     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513)
#17     _rootRun (dart:async/zone.dart:1124)
#18     _CustomZone.run (dart:async/zone.dart:1021)
#19     _CustomZone.runGuarded (dart:async/zone.dart:923)
#20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)

0314 17:27:48 [Debug] :  AppLifecycleState.inactive
0314 17:27:48 [Debug] :  AppLifecycleState.paused
0314 17:27:51 [Debug] :  [Received] <== event.state_changed: sun.sun
0314 17:28:22 [Debug] :  [Received] <== event.state_changed: sensor.time
0314 17:28:22 [Debug] :  New entity. Need to rebuild UI
0314 17:28:22 [Debug] :  Use lovelace is true
0314 17:28:22 [Debug] :  [Sending] ==> {"id": 231, "type": "get_states"}
0314 17:28:22 [Debug] :  [Sending] ==> {"id": 232, "type": "lovelace/config"}
0314 17:28:22 [Debug] :  [Sending] ==> {"id": 233, "type": "get_config"}
0314 17:28:22 [Debug] :  [Sending] ==> {"id": 234, "type": "get_services"}
0314 17:28:22 [Debug] :  [Sending] ==> {"id": 235, "type": "auth/current_user"}
0314 17:28:22 [Debug] :  [Sending] ==> {"id": 236, "type": "get_panels"}
0314 17:28:23 [Debug] :  [Received] <== id:231, success
0314 17:28:23 [Debug] :  Parsing 183 Home Assistant entities
0314 17:28:23 [Debug] :  [Received] <== id:233, success
0314 17:28:23 [Debug] :  [Received] <== id:236, success
0314 17:28:23 [Debug] :  [Received] <== id:232, success
0314 17:28:23 [Debug] :  [Received] <== id:234, success
0314 17:28:23 [Debug] :  We actually don`t need the list of servcies for now
0314 17:28:23 [Debug] :  [Received] <== id:235, success
0314 17:28:23 [Error] :  NoSuchMethodError: The method '*' was called on null.
Receiver: null
Tried calling: *()
0314 17:28:23 [Error] :  #0      new Duration. (dart:core/duration.dart:103)
#1      TimerEntity.update (file:///home/estevez/src/ha_client/lib/entity_class/timer_entity.dart:10)
#2      new Entity. (file:///home/estevez/src/ha_client/lib/entity_class/entity.class.dart:119)
#3      new TimerEntity. (file:///home/estevez/src/ha_client/lib/entity_class/timer_entity.dart:4)
#4      EntityCollection._createEntityInstance (file:///home/estevez/src/ha_client/lib/entity_collection.class.dart:37)
#5      EntityCollection.addFromRaw (file:///home/estevez/src/ha_client/lib/entity_collection.class.dart:119)
#6      EntityCollection.parse.<anonymous closure> (file:///home/estevez/src/ha_client/lib/entity_collection.class.dart:24)
#7      _GrowableList.forEach (dart:core/runtime/libgrowable_array.dart:278)
#8      EntityCollection.parse (file:///home/estevez/src/ha_client/lib/entity_collection.class.dart:23)
#9      HomeAssistant._getStates.<anonymous closure> (file:///home/estevez/src/ha_client/lib/home_assistant.class.dart:244)
#10     _rootRunUnary (dart:async/zone.dart:1132)
#11     _CustomZone.runUnary (dart:async/zone.dart:1029)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:126)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639)
#14     Future._propagateToListeners (dart:async/future_impl.dart:668)
#15     Future._completeWithValue (dart:async/future_impl.dart:483)
#16     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513)
#17     _rootRun (dart:async/zone.dart:1124)
#18     _CustomZone.run (dart:async/zone.dart:1021)
#19     _CustomZone.runGuarded (dart:async/zone.dart:923)
#20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)

0314 17:28:51 [Debug] :  [Received] <== event.state_changed: sun.sun
0314 17:29:18 [Debug] :  AppLifecycleState.inactive
0314 17:29:18 [Debug] :  AppLifecycleState.resumed
0314 17:29:18 [Debug] :  Use lovelace is true
0314 17:29:18 [Debug] :  [Sending] ==> {"id": 237, "type": "get_states"}
0314 17:29:18 [Debug] :  [Sending] ==> {"id": 238, "type": "lovelace/config"}
0314 17:29:18 [Debug] :  [Sending] ==> {"id": 239, "type": "get_config"}
0314 17:29:18 [Debug] :  [Sending] ==> {"id": 240, "type": "get_services"}
0314 17:29:18 [Debug] :  [Sending] ==> {"id": 241, "type": "auth/current_user"}
0314 17:29:18 [Debug] :  [Sending] ==> {"id": 242, "type": "get_panels"}
0314 17:29:18 [Debug] :  [Received] <== id:237, success
0314 17:29:18 [Debug] :  Parsing 183 Home Assistant entities
0314 17:29:18 [Debug] :  [Received] <== id:239, success
0314 17:29:18 [Debug] :  [Received] <== id:242, success
0314 17:29:18 [Debug] :  [Received] <== id:238, success
0314 17:29:18 [Debug] :  [Received] <== id:240, success
0314 17:29:18 [Debug] :  We actually don`t need the list of servcies for now
0314 17:29:18 [Debug] :  [Received] <== id:241, success
0314 17:29:18 [Error] :  NoSuchMethodError: The method '*' was called on null.
Receiver: null
Tried calling: *()
0314 17:29:18 [Error] :  #0      new Duration. (dart:core/duration.dart:103)
#1      TimerEntity.update (file:///home/estevez/src/ha_client/lib/entity_class/timer_entity.dart:10)
#2      new Entity. (file:///home/estevez/src/ha_client/lib/entity_class/entity.class.dart:119)
#3      new TimerEntity. (file:///home/estevez/src/ha_client/lib/entity_class/timer_entity.dart:4)
#4      EntityCollection._createEntityInstance (file:///home/estevez/src/ha_client/lib/entity_collection.class.dart:37)
#5      EntityCollection.addFromRaw (file:///home/estevez/src/ha_client/lib/entity_collection.class.dart:119)
#6      EntityCollection.parse.<anonymous closure> (file:///home/estevez/src/ha_client/lib/entity_collection.class.dart:24)
#7      _GrowableList.forEach (dart:core/runtime/libgrowable_array.dart:278)
#8      EntityCollection.parse (file:///home/estevez/src/ha_client/lib/entity_collection.class.dart:23)
#9      HomeAssistant._getStates.<anonymous closure> (file:///home/estevez/src/ha_client/lib/home_assistant.class.dart:244)
#10     _rootRunUnary (dart:async/zone.dart:1132)
#11     _CustomZone.runUnary (dart:async/zone.dart:1029)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:126)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639)
#14     Future._propagateToListeners (dart:async/future_impl.dart:668)
#15     Future._completeWithValue (dart:async/future_impl.dart:483)
#16     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513)
#17     _rootRun (dart:async/zone.dart:1124)
#18     _CustomZone.run (dart:async/zone.dart:1021)
#19     _CustomZone.runGuarded (dart:async/zone.dart:923)
#20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)

0314 17:29:19 [Debug] :  Use lovelace is true
0314 17:29:19 [Debug] :  [Sending] ==> {"id": 243, "type": "get_states"}
0314 17:29:19 [Debug] :  [Sending] ==> {"id": 244, "type": "lovelace/config"}
0314 17:29:19 [Debug] :  [Sending] ==> {"id": 245, "type": "get_config"}
0314 17:29:19 [Debug] :  [Sending] ==> {"id": 246, "type": "get_services"}
0314 17:29:19 [Debug] :  [Sending] ==> {"id": 247, "type": "auth/current_user"}
0314 17:29:19 [Debug] :  [Sending] ==> {"id": 248, "type": "get_panels"}
0314 17:29:20 [Debug] :  [Received] <== id:243, success
0314 17:29:20 [Debug] :  Parsing 183 Home Assistant entities
0314 17:29:20 [Debug] :  [Received] <== id:245, success
0314 17:29:20 [Debug] :  [Received] <== id:248, success
0314 17:29:21 [Debug] :  [Received] <== id:244, success
0314 17:29:21 [Debug] :  [Received] <== id:246, success
0314 17:29:21 [Debug] :  We actually don`t need the list of servcies for now
0314 17:29:21 [Debug] :  [Received] <== id:247, success
0314 17:29:21 [Error] :  NoSuchMethodError: The method '*' was called on null.
Receiver: null
Tried calling: *()
0314 17:29:21 [Error] :  #0      new Duration. (dart:core/duration.dart:103)
#1      TimerEntity.update (file:///home/estevez/src/ha_client/lib/entity_class/timer_entity.dart:10)
#2      new Entity. (file:///home/estevez/src/ha_client/lib/entity_class/entity.class.dart:119)
#3      new TimerEntity. (file:///home/estevez/src/ha_client/lib/entity_class/timer_entity.dart:4)
#4      EntityCollection._createEntityInstance (file:///home/estevez/src/ha_client/lib/entity_collection.class.dart:37)
#5      EntityCollection.addFromRaw (file:///home/estevez/src/ha_client/lib/entity_collection.class.dart:119)
#6      EntityCollection.parse.<anonymous closure> (file:///home/estevez/src/ha_client/lib/entity_collection.class.dart:24)
#7      _GrowableList.forEach (dart:core/runtime/libgrowable_array.dart:278)
#8      EntityCollection.parse (file:///home/estevez/src/ha_client/lib/entity_collection.class.dart:23)
#9      HomeAssistant._getStates.<anonymous closure> (file:///home/estevez/src/ha_client/lib/home_assistant.class.dart:244)
#10     _rootRunUnary (dart:async/zone.dart:1132)
#11     _CustomZone.runUnary (dart:async/zone.dart:1029)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:126)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639)
#14     Future._propagateToListeners (dart:async/future_impl.dart:668)
#15     Future._completeWithValue (dart:async/future_impl.dart:483)
#16     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513)
#17     _rootRun (dart:async/zone.dart:1124)
#18     _CustomZone.run (dart:async/zone.dart:1021)
#19     _CustomZone.runGuarded (dart:async/zone.dart:923)
#20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)

0314 17:29:22 [Debug] :  [Received] <== event.state_changed: sensor.time
0314 17:29:22 [Debug] :  New entity. Need to rebuild UI
0314 17:29:22 [Debug] :  Use lovelace is true
0314 17:29:22 [Debug] :  [Sending] ==> {"id": 249, "type": "get_states"}
0314 17:29:22 [Debug] :  [Sending] ==> {"id": 250, "type": "lovelace/config"}
0314 17:29:22 [Debug] :  [Sending] ==> {"id": 251, "type": "get_config"}
0314 17:29:22 [Debug] :  [Sending] ==> {"id": 252, "type": "get_services"}
0314 17:29:22 [Debug] :  [Sending] ==> {"id": 253, "type": "auth/current_user"}
0314 17:29:22 [Debug] :  [Sending] ==> {"id": 254, "type": "get_panels"}
0314 17:29:23 [Debug] :  [Received] <== id:249, success
0314 17:29:23 [Debug] :  Parsing 183 Home Assistant entities
0314 17:29:23 [Debug] :  [Received] <== id:251, success
0314 17:29:23 [Debug] :  [Received] <== id:254, success
0314 17:29:23 [Debug] :  [Received] <== id:250, success
0314 17:29:23 [Debug] :  [Received] <== id:252, success
0314 17:29:23 [Debug] :  We actually don`t need the list of servcies for now
0314 17:29:23 [Debug] :  [Received] <== id:253, success
0314 17:29:23 [Error] :  NoSuchMethodError: The method '*' was called on null.
Receiver: null
Tried calling: *()
0314 17:29:23 [Error] :  #0      new Duration. (dart:core/duration.dart:103)
#1      TimerEntity.update (file:///home/estevez/src/ha_client/lib/entity_class/timer_entity.dart:10)
#2      new Entity. (file:///home/estevez/src/ha_client/lib/entity_class/entity.class.dart:119)
#3      new TimerEntity. (file:///home/estevez/src/ha_client/lib/entity_class/timer_entity.dart:4)
#4      EntityCollection._createEntityInstance (file:///home/estevez/src/ha_client/lib/entity_collection.class.dart:37)
#5      EntityCollection.addFromRaw (file:///home/estevez/src/ha_client/lib/entity_collection.class.dart:119)
#6      EntityCollection.parse.<anonymous closure> (file:///home/estevez/src/ha_client/lib/entity_collection.class.dart:24)
#7      _GrowableList.forEach (dart:core/runtime/libgrowable_array.dart:278)
#8      EntityCollection.parse (file:///home/estevez/src/ha_client/lib/entity_collection.class.dart:23)
#9      HomeAssistant._getStates.<anonymous closure> (file:///home/estevez/src/ha_client/lib/home_assistant.class.dart:244)
#10     _rootRunUnary (dart:async/zone.dart:1132)
#11     _CustomZone.runUnary (dart:async/zone.dart:1029)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:126)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639)
#14     Future._propagateToListeners (dart:async/future_impl.dart:668)
#15     Future._completeWithValue (dart:async/future_impl.dart:483)
#16     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513)
#17     _rootRun (dart:async/zone.dart:1124)
#18     _CustomZone.run (dart:async/zone.dart:1021)
#19     _CustomZone.runGuarded (dart:async/zone.dart:923)
#20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
```

**Comment by estevez-dev** [comment]
Fill free to reopen if the issue will still present in 0.5.2

**Comment by Kvasenok** [comment]
Wow, that was fast)) Thanks)

Will check and reopen if something goes wrong.
