### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by estevez-dev** [estevez-dev/ha_client#363]
```
0405 21:07:36 [Debug] :  [Received] <== event.state_changed: sensor.lumi_lumiweather_02772e8d_1_temperature
0405 21:07:36 [Debug] :  [Received] <== event.state_changed: sensor.lumi_lumiweather_02772e8d_1_temperature
0405 21:07:39 [Debug] :  [Received] <== event.state_changed: zha_new.controller
0405 21:07:39 [Debug] :  [Received] <== event.state_changed: zha_new.controller
0405 21:07:39 [Debug] :  [Received] <== event.state_changed: sensor.cpu_temperature
0405 21:07:39 [Debug] :  [Received] <== event.state_changed: sensor.cpu_temperature
0405 21:07:44 [Debug] :  [Received] <== event.state_changed: binary_sensor.lumi_lumiremoteb1acn01_01ef39e8_1
0405 21:07:44 [Debug] :  [Received] <== event.state_changed: binary_sensor.lumi_lumiremoteb1acn01_01ef39e8_1
0405 21:08:00 [Debug] :  [Received] <== event.state_changed: sensor.time
0405 21:08:00 [Debug] :  [Received] <== event.state_changed: sensor.time
0405 21:08:05 [Debug] :  [Received] <== event.state_changed: sensor.lumi_lumiweather_02772e8d_1_pressure
0405 21:08:05 [Debug] :  [Received] <== event.state_changed: sensor.lumi_lumiweather_02772e8d_1_pressure
0405 21:08:05 [Debug] :  [Received] <== event.state_changed: sensor.lumi_lumiweather_02772e8d_1_humidity
0405 21:08:05 [Debug] :  [Received] <== event.state_changed: sensor.lumi_lumiweather_02772e8d_1_humidity
0405 21:08:29 [Debug] :  [Received] <== event.state_changed: sun.sun
0405 21:08:29 [Debug] :  [Received] <== event.state_changed: sun.sun
0405 21:08:40 [Debug] :  [Received] <== event.state_changed: zha_new.controller
0405 21:08:40 [Debug] :  [Received] <== event.state_changed: zha_new.controller
0405 21:09:00 [Debug] :  [Received] <== event.state_changed: sensor.time
0405 21:09:00 [Debug] :  [Received] <== event.state_changed: sensor.time
0405 21:09:29 [Debug] :  [Received] <== event.state_changed: sun.sun
0405 21:09:29 [Debug] :  [Received] <== event.state_changed: sun.sun
0405 21:09:41 [Debug] :  [Received] <== event.state_changed: zha_new.controller
0405 21:09:41 [Debug] :  [Received] <== event.state_changed: zha_new.controller
0405 21:09:41 [Debug] :  [Received] <== event.state_changed: sensor.cpu_temperature
0405 21:09:41 [Debug] :  [Received] <== event.state_changed: sensor.cpu_temperature
0405 21:09:50 [Debug] :  Socket disconnected.
0405 21:09:50 [Debug] :  Socket disconnecting...
0405 21:09:50 [Debug] :  ..Disconnected
0405 21:09:55 [Debug] :  Trying to reconnect...
0405 21:09:55 [Debug] :  Socket disconnecting...
0405 21:09:55 [Debug] :  ..Disconnected
0405 21:09:55 [Debug] :  Socket connecting...
0405 21:10:42 [Debug] :  AppLifecycleState.inactive
0405 21:10:42 [Debug] :  AppLifecycleState.resumed
0405 21:10:42 [Warning] :  Previous connection attempt pending...
0405 21:10:45 [Debug] :  Current colotfor picker: [180.0, 0.4]
0405 21:10:45 [Debug] :  [Sending] ==> https://ha.homemade.systems:8123/api/history/period/2019-04-04T21:10:45+0300?&filter_entity_id=light.living_room_backlight
0405 21:10:45 [Debug] :  [Received] <== 5 history recors
0405 21:10:47 [Debug] :  HS Color: [60.0, 0.2]
0405 21:10:47 [Warning] :  Previous connection attempt pending...
0405 21:10:47 [Debug] :  Current colotfor picker: [60.0, 0.2]
0405 21:10:56 [Debug] :  Current colotfor picker: [180.0, 0.4]
0405 21:10:56 [Debug] :  [Sending] ==> https://ha.homemade.systems:8123/api/history/period/2019-04-04T21:10:56+0300?&filter_entity_id=light.living_room_backlight
0405 21:10:56 [Debug] :  [Received] <== 5 history recors
0405 21:10:57 [Debug] :  Socket disconnecting...
0405 21:10:57 [Warning] :  Previous connection attempt pending...
0405 21:10:57 [Warning] :  Previous connection attempt pending...
0405 21:10:57 [Warning] :  Previous connection attempt pending...
0405 21:10:57 [Warning] :  Previous connection attempt pending...
0405 21:10:57 [Warning] :  Previous connection attempt pending...
0405 21:10:57 [Warning] :  Previous connection attempt pending...
0405 21:10:58 [Debug] :  HS Color: [60.0, 0.2]
0405 21:10:58 [Warning] :  Previous connection attempt pending...
0405 21:10:58 [Debug] :  Current colotfor picker: [60.0, 0.2]
0405 21:11:00 [Debug] :  Socket sink close timeout
0405 21:11:00 [Debug] :  ..Disconnected
0405 21:11:00 [Error] :  Bad state: Future already completed
0405 21:11:00 [Error] :  #0      _Completer.completeError (dart:async/future_impl.dart:21:31)
#1      Connection._doConnect.<anonymous closure>.<anonymous closure> (file:///home/estevez/src/ha_client/lib/connection.class.dart:90:21)
#2      _rootRunUnary (dart:async/zone.dart:1132:38)
#3      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#6      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#7      Future._complete (dart:async/future_impl.dart:473:7)
#8      _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#9      _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#10     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
#11     Connection._disconnect (file:///home/estevez/src/ha_client/lib/connection.class.dart)
<asynchronous suspension>
#12     Connection._doConnect.<anonymous closure> (file:///home/estevez/src/ha_client/lib/connection.class.dart:89:9)
#13     _rootRun (dart:async/zone.dart:1120:38)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     Future.timeout.<anonymous closure> (dart:async/future_impl.dart:728:33)
#16     _rootRun (dart:async/zone.dart:1120:38)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#20     _rootRun (dart:async/zone.dart:1124:13)
#21     _CustomZone.run (dart:async/zone.dart:1021:19)
#22     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#23     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#24     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#25     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#26     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

0405 21:11:02 [Debug] :  [Sending] ==> {"type":"call_service","id":32,"domain":"light","service":"turn_on","service_data":{"entity_id":"light.living_room_backlight","hs_color":[60.0,20.0]}}
0405 21:11:02 [Error] :  Bad state: Future already completed
0405 21:11:02 [Error] :  #0      _Completer.completeError (dart:async/future_impl.dart:21:31)
#1      Connection.sendSocketMessage.<anonymous closure> (file:///home/estevez/src/ha_client/lib/connection.class.dart:309:20)
#2      _rootRunUnary (dart:async/zone.dart:1132:38)
#3      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#4      _FutureListener.handleError (dart:async/future_impl.dart:144:20)
#5      Future._propagateToListeners.handleError (dart:async/future_impl.dart:651:47)
#6      Future._propagateToListeners (dart:async/future_impl.dart:672:24)
#7      Future._complete (dart:async/future_impl.dart:473:7)
#8      Future.timeout.<anonymous closure> (dart:async/future_impl.dart:728:18)
#9      _rootRun (dart:async/zone.dart:1120:38)
#10     _CustomZone.run (dart:async/zone.dart:1021:19)
#11     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#13     _rootRun (dart:async/zone.dart:1124:13)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#16     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#17     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#18     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#19     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

0405 21:11:05 [Debug] :  HS Color: [120.0, 0.2]
0405 21:11:05 [Warning] :  Previous connection attempt pending...
0405 21:11:05 [Debug] :  Current colotfor picker: [120.0, 0.2]
0405 21:11:07 [Debug] :  HS Color: [105.0, 0.6]
0405 21:11:07 [Warning] :  Previous connection attempt pending...
0405 21:11:07 [Debug] :  Current colotfor picker: [105.0, 0.6]
0405 21:11:12 [Debug] :  [Sending] ==> {"type":"get_states","id":33}
0405 21:11:12 [Error] :  Bad state: Future already completed
0405 21:11:12 [Error] :  #0      _Completer.completeError (dart:async/future_impl.dart:21:31)
#1      Connection.sendSocketMessage.<anonymous closure> (file:///home/estevez/src/ha_client/lib/connection.class.dart:309:20)
#2      _rootRunUnary (dart:async/zone.dart:1132:38)
#3      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#4      _FutureListener.handleError (dart:async/future_impl.dart:144:20)
#5      Future._propagateToListeners.handleError (dart:async/future_impl.dart:651:47)
#6      Future._propagateToListeners (dart:async/future_impl.dart:672:24)
#7      Future._complete (dart:async/future_impl.dart:473:7)
#8      Future.timeout.<anonymous closure> (dart:async/future_impl.dart:728:18)
#9      _rootRun (dart:async/zone.dart:1120:38)
#10     _CustomZone.run (dart:async/zone.dart:1021:19)
#11     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#13     _rootRun (dart:async/zone.dart:1124:13)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#16     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#17     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#18     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#19     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

0405 21:11:12 [Debug] :  [Sending] ==> {"type":"lovelace/config","id":34}
0405 21:11:12 [Error] :  Bad state: Future already completed
0405 21:11:12 [Error] :  #0      _Completer.completeError (dart:async/future_impl.dart:21:31)
#1      Connection.sendSocketMessage.<anonymous closure> (file:///home/estevez/src/ha_client/lib/connection.class.dart:309:20)
#2      _rootRunUnary (dart:async/zone.dart:1132:38)
#3      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#4      _FutureListener.handleError (dart:async/future_impl.dart:144:20)
#5      Future._propagateToListeners.handleError (dart:async/future_impl.dart:651:47)
#6      Future._propagateToListeners (dart:async/future_impl.dart:672:24)
#7      Future._complete (dart:async/future_impl.dart:473:7)
#8      Future.timeout.<anonymous closure> (dart:async/future_impl.dart:728:18)
#9      _rootRun (dart:async/zone.dart:1120:38)
#10     _CustomZone.run (dart:async/zone.dart:1021:19)
#11     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#13     _rootRun (dart:async/zone.dart:1124:13)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#16     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#17     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#18     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#19     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

0405 21:11:12 [Debug] :  [Sending] ==> {"type":"get_config","id":35}
0405 21:11:12 [Error] :  Bad state: Future already completed
0405 21:11:12 [Error] :  #0      _Completer.completeError (dart:async/future_impl.dart:21:31)
#1      Connection.sendSocketMessage.<anonymous closure> (file:///home/estevez/src/ha_client/lib/connection.class.dart:309:20)
#2      _rootRunUnary (dart:async/zone.dart:1132:38)
#3      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#4      _FutureListener.handleError (dart:async/future_impl.dart:144:20)
#5      Future._propagateToListeners.handleError (dart:async/future_impl.dart:651:47)
#6      Future._propagateToListeners (dart:async/future_impl.dart:672:24)
#7      Future._complete (dart:async/future_impl.dart:473:7)
#8      Future.timeout.<anonymous closure> (dart:async/future_impl.dart:728:18)
#9      _rootRun (dart:async/zone.dart:1120:38)
#10     _CustomZone.run (dart:async/zone.dart:1021:19)
#11     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#13     _rootRun (dart:async/zone.dart:1124:13)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#16     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#17     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#18     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#19     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

0405 21:11:12 [Debug] :  [Sending] ==> {"type":"get_services","id":36}
0405 21:11:12 [Error] :  Bad state: Future already completed
0405 21:11:12 [Error] :  #0      _Completer.completeError (dart:async/future_impl.dart:21:31)
#1      Connection.sendSocketMessage.<anonymous closure> (file:///home/estevez/src/ha_client/lib/connection.class.dart:309:20)
#2      _rootRunUnary (dart:async/zone.dart:1132:38)
#3      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#4      _FutureListener.handleError (dart:async/future_impl.dart:144:20)
#5      Future._propagateToListeners.handleError (dart:async/future_impl.dart:651:47)
#6      Future._propagateToListeners (dart:async/future_impl.dart:672:24)
#7      Future._complete (dart:async/future_impl.dart:473:7)
#8      Future.timeout.<anonymous closure> (dart:async/future_impl.dart:728:18)
#9      _rootRun (dart:async/zone.dart:1120:38)
#10     _CustomZone.run (dart:async/zone.dart:1021:19)
#11     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#13     _rootRun (dart:async/zone.dart:1124:13)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#16     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#17     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#18     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#19     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

0405 21:11:12 [Debug] :  [Sending] ==> {"type":"auth/current_user","id":37}
0405 21:11:12 [Error] :  Bad state: Future already completed
0405 21:11:12 [Error] :  #0      _Completer.completeError (dart:async/future_impl.dart:21:31)
#1      Connection.sendSocketMessage.<anonymous closure> (file:///home/estevez/src/ha_client/lib/connection.class.dart:309:20)
#2      _rootRunUnary (dart:async/zone.dart:1132:38)
#3      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#4      _FutureListener.handleError (dart:async/future_impl.dart:144:20)
#5      Future._propagateToListeners.handleError (dart:async/future_impl.dart:651:47)
#6      Future._propagateToListeners (dart:async/future_impl.dart:672:24)
#7      Future._complete (dart:async/future_impl.dart:473:7)
#8      Future.timeout.<anonymous closure> (dart:async/future_impl.dart:728:18)
#9      _rootRun (dart:async/zone.dart:1120:38)
#10     _CustomZone.run (dart:async/zone.dart:1021:19)
#11     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#13     _rootRun (dart:async/zone.dart:1124:13)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#16     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#17     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#18     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#19     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

0405 21:11:12 [Debug] :  [Sending] ==> {"type":"get_panels","id":38}
0405 21:11:12 [Error] :  Bad state: Future already completed
0405 21:11:12 [Error] :  #0      _Completer.completeError (dart:async/future_impl.dart:21:31)
#1      Connection.sendSocketMessage.<anonymous closure> (file:///home/estevez/src/ha_client/lib/connection.class.dart:309:20)
#2      _rootRunUnary (dart:async/zone.dart:1132:38)
#3      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#4      _FutureListener.handleError (dart:async/future_impl.dart:144:20)
#5      Future._propagateToListeners.handleError (dart:async/future_impl.dart:651:47)
#6      Future._propagateToListeners (dart:async/future_impl.dart:672:24)
#7      Future._complete (dart:async/future_impl.dart:473:7)
#8      Future.timeout.<anonymous closure> (dart:async/future_impl.dart:728:18)
#9      _rootRun (dart:async/zone.dart:1120:38)
#10     _CustomZone.run (dart:async/zone.dart:1021:19)
#11     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#13     _rootRun (dart:async/zone.dart:1124:13)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#16     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#17     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#18     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#19     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

0405 21:11:12 [Warning] :  Can't get services: {errorCode: 8, errorMessage: No connection to Home Assistant}
0405 21:11:12 [Warning] :  Can't get user info: {errorCode: 8, errorMessage: No connection to Home Assistant}
0405 21:11:12 [Debug] :  Current colotfor picker: [180.0, 0.4]
0405 21:11:12 [Debug] :  History was updated 16 seconds ago
0405 21:11:13 [Debug] :  [Sending] ==> {"type":"call_service","id":39,"domain":"light","service":"turn_on","service_data":{"entity_id":"light.living_room_backlight","hs_color":[60.0,20.0]}}
0405 21:11:13 [Error] :  Bad state: Future already completed
0405 21:11:13 [Error] :  #0      _Completer.completeError (dart:async/future_impl.dart:21:31)
#1      Connection.sendSocketMessage.<anonymous closure> (file:///home/estevez/src/ha_client/lib/connection.class.dart:309:20)
#2      _rootRunUnary (dart:async/zone.dart:1132:38)
#3      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#4      _FutureListener.handleError (dart:async/future_impl.dart:144:20)
#5      Future._propagateToListeners.handleError (dart:async/future_impl.dart:651:47)
#6      Future._propagateToListeners (dart:async/future_impl.dart:672:24)
#7      Future._complete (dart:async/future_impl.dart:473:7)
#8      Future.timeout.<anonymous closure> (dart:async/future_impl.dart:728:18)
#9      _rootRun (dart:async/zone.dart:1120:38)
#10     _CustomZone.run (dart:async/zone.dart:1021:19)
#11     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#13     _rootRun (dart:async/zone.dart:1124:13)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#16     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#17     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#18     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#19     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

0405 21:11:14 [Warning] :  Previous connection attempt pending...
0405 21:11:16 [Warning] :  Previous connection attempt pending...
0405 21:11:18 [Error] :  setState() called after dispose(): _SwitchStateWidgetState#75da3(lifecycle state: defunct, not mounted)
This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback. The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
0405 21:11:18 [Error] :  #0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1095:9)
#1      State.setState (package:flutter/src/widgets/framework.dart:1121:6)
#2      _SwitchStateWidgetState._setNewState.<anonymous closure> (file:///home/estevez/src/ha_client/lib/entity_widgets/state/switch_state.dart:29:7)
#3      _rootRun (dart:async/zone.dart:1120:38)
#4      _CustomZone.run (dart:async/zone.dart:1021:19)
#5      _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#6      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#7      _rootRun (dart:async/zone.dart:1124:13)
#8      _CustomZone.run (dart:async/zone.dart:1021:19)
#9      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#10     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#11     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#12     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#13     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

0405 21:11:20 [Debug] :  [Sending] ==> {"type":"call_service","id":40,"domain":"light","service":"turn_on","service_data":{"entity_id":"light.living_room_backlight","hs_color":[120.0,20.0]}}
0405 21:11:20 [Error] :  Bad state: Future already completed
0405 21:11:20 [Error] :  #0      _Completer.completeError (dart:async/future_impl.dart:21:31)
#1      Connection.sendSocketMessage.<anonymous closure> (file:///home/estevez/src/ha_client/lib/connection.class.dart:309:20)
#2      _rootRunUnary (dart:async/zone.dart:1132:38)
#3      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#4      _FutureListener.handleError (dart:async/future_impl.dart:144:20)
#5      Future._propagateToListeners.handleError (dart:async/future_impl.dart:651:47)
#6      Future._propagateToListeners (dart:async/future_impl.dart:672:24)
#7      Future._complete (dart:async/future_impl.dart:473:7)
#8      Future.timeout.<anonymous closure> (dart:async/future_impl.dart:728:18)
#9      _rootRun (dart:async/zone.dart:1120:38)
#10     _CustomZone.run (dart:async/zone.dart:1021:19)
#11     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#13     _rootRun (dart:async/zone.dart:1124:13)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#16     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#17     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#18     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#19     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

**Comment by estevez-dev** [comment]
Looks like the reason is the same as in #364
