### ISSUE TITLE
Can't use portrait mode. Landscape mode works

### ISSUE THREAD

**Issue by backcountrymountains** [estevez-dev/ha_client#486]
Android 6.0.1 old phone with a small screen is having trouble with 0.7.0
The views work fine in landscape mode, but I get a blank screen in portrait mode.

How do I roll-back to 0.6.7?

`
1029 10:54:08 [Debug] :  [Received] <== HTTP 200
1029 10:54:08 [Debug] :  App registration works fine
1029 10:54:42 [Error] :  NoSuchMethodError: The method 'contains' was called on null.
Receiver: null
Tried calling: contains()
1029 10:54:42 [Error] :  #0      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2127)
#1      RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure> (package:flutter/src/rendering/box.dart:2481)
#2      BoxHitTestResult.addWithRawTransform (package:flutter/src/rendering/box.dart:795)
#3      BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:752)
#4      RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2476)
#5      RenderCustomLayoutBox.hitTestChildren (package:hass_client/plugins/dynamic_multi_column_layout.dart:139)
#6      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2128)
#7      RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114)
#8      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2128)
#9      RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114)
#10     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2128)
#11     RenderSliverHelpers.hitTestBoxChild.<anonymous closure> (package:flutter/src/rendering/sliver.dart:1660)
#12     BoxHitTestResult.addWithRawTransform (package:flutter/src/rendering/box.dart:795)
#13     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:752)
#14     RenderSliverHelpers.hitTestBoxChild (package:flutter/src/rendering/sliver.dart:1656)
#15     RenderSliverMultiBoxAdaptor.hitTestChildren (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:564)
#16     RenderSliver.hitTest (package:flutter/src/rendering/sliver.dart:1275)
#17     SliverHitTestResult.addWithAxisOffset (package:flutter/src/rendering/sliver.dart:847)
#18     RenderSliverPadding.hitTestChildren (package:flutter/src/rendering/sliver_padding.dart:266)
#19     RenderSliver.hitTest (package:flutter/src/rendering/sliver.dart:1275)
#20     RenderViewportBase.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/viewport.dart:585)
#21     BoxHitTestResult.addWithRawTransform (package:flutter/src/rendering/box.dart:795)
#22     BoxHitTestResult.addWithPaintTransform (package:flutter/src/rendering/box.dart:723)
#23     RenderViewportBase.hitTestChildren (package:flutter/src/rendering/viewport.dart:576)
#24     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2128)
#25     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114)
#26     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2128)
#27     RenderIgnorePointer.hitTest (package:flutter/src/rendering/proxy_box.dart:3036)
#28     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114)
#29     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2128)
#30     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114)
#31     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:161)
#32     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114)
#33     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2128)
#34     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114)
#35     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:161)
#36     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114)
#37     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2128)
#38     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114)
#39     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2128)
#40     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114)
#41     RenderCustomPaint.hitTestChildren (package:flutter/src/rendering/custom_paint.dart:508)
#42     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2128)
#43     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114)
#44     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2128)
#45     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114)
#46     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2128)
#47     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114)
#48     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2128)
#49     RenderSliverHelpers.hitTestBoxChild.<anonymous closure> (package:flutter/src/rendering/sliver.dart:1660)
#50     BoxHitTestResult.addWithRawTransform (package:flutter/src/rendering/box.dart:795)
#51     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:752)
#52     RenderSliverHelpers.hitTestBoxChild (package:flutter/src/rendering/sliver.dart:1656)
#53     RenderSliverMultiBoxAdaptor.hitTestChildren (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:564)
#54     RenderSliver.hitTest (package:flutter/src/rendering/sliver.dart:1275)
#55     RenderViewportBase.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/viewport.dart:585)
#56     BoxHitTestResult.addWithRawTransform (package:flutter/src/rendering/box.dart:795)
#57     BoxHitTestResult.addWithPaintTransform (package:flutter/src/rendering/box.dart:723)
#58     RenderViewportBase.hitTestChildren (package:flutter/src/rendering/viewport.dart:576)
#59     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2128)
#60     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114)
#61     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2128)
#62     RenderIgnorePointer.hitTest (package:flutter/src/rendering/proxy_box.dart:3036)
#63     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114)
#64     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2128)
#65     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114)
#66     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:161)
#67     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114)
#68     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2128)
#69     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114)
#70     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:161)
#71     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114)
#72     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2128)
#73     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114)
#74     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2128)
#75     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114)
#76     RenderCustomPaint.hitTestChildren (package:flutter/src/rendering/custom_paint.dart:508)
#77     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2128)
#78     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114)
#79     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2128)
#80     RenderSliverHelpers.hitTestBoxChild.<anonymous closure> (package:flutter/src/rendering/sliver.dart:1660)
#81     BoxHitTestResult.addWithRawTransform (package:flutter/src/rendering/box.dart:795)
#82     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:752)
#83     RenderSliverHelpers.hitTestBoxChild (package:flutter/src/rendering/sliver.dart:1656)
#84     RenderSliverSingleBoxAdapter.hitTestChildren (package:flutter/src/rendering/sliver.dart:1750)
#85     RenderSliver.hitTest (package:flutter/src/rendering/sliver.dart:1275)
#86     RenderViewportBase.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/viewport.dart:585)
#87     BoxHitTestResult.addWithRawTransform (package:flutter/src/rendering/box.dart:795)
#88     BoxHitTestResult.addWithPaintTransform (package:flutter/src/rendering/box.dart:723)
#89     RenderViewportBase.hitTestChildren (package:flutter/src/rendering/viewport.dart:576)
#90     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2128)
#91     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114)
#92     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2128)
#93     RenderIgnorePointer.hitTest (package:flutter/src/rendering/proxy_box.dart:3036)
#94     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114)
#95     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2128)
#96     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114)
#97     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:161)
#98     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114)
#99     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2128)
#100    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114)
#101    RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:161)
#102    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114)
#103    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2128)
#104    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114)
#105    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2128)
#106    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114)
#107    RenderCustomPaint.hitTestChildren (package:flutter/src/rendering/custom_paint.dart:508)
#108    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2128)
#109    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114)
#110    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2128)
#111    RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure> (package:flutter/src/rendering/box.dart:2481)
#112    BoxHitTestResult.addWithRawTransform (package:flutter/src/rendering/box.dart:795)
#113    BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:752)
#114    RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2476)
#115    RenderCustomMultiChildLayoutBox.hitTestChildren (package:flutter/src/rendering/custom_layout.dart:366)
#116    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2128)
#117    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114)
#118    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2128)
#119    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114)
#120    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2128)
#121    RenderPhysicalModel.hitTest (package:flutter/src/rendering/proxy_box.dart:1716)
#122    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114)
#123    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2128)
#124    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114)
#125    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2128)
#126    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114)
#127    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2128)
#128    RenderIgnorePointer.hitTest (package:flutter/src/rendering/proxy_box.dart:3036)
#129    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114)
#130    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2128)
#131    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114)
#132    RenderFractionalTranslation.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/proxy_box.dart:2447)
#133    BoxHitTestResult.addWithRawTransform (package:flutter/src/rendering/box.dart:795)
#134    BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:752)
#135    RenderFractionalTranslation.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:2441)
#136    RenderFractionalTranslation.hitTest (package:flutter/src/rendering/proxy_box.dart:2427)
#137    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114)
#138    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2128)
#139    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114)
#140    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2128)
#141    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114)
#142    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2128)
#143    RenderOffstage.hitTest (package:flutter/src/rendering/proxy_box.dart:3146)
#144    RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure> (package:flutter/src/rendering/box.dart:2481)
#145    BoxHitTestResult.addWithRawTransform (package:flutter/src/rendering/box.dart:795)
#146    BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:752)
#147    RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2476)
#148    RenderStack.hitTestChildren (package:flutter/src/rendering/stack.dart:585)
#149    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2128)
#150    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114)
#151    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2128)
#152    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114)
#153    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2128)
#154    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114)
#155    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2128)
#156    RenderAbsorbPointer.hitTest (package:flutter/src/rendering/proxy_box.dart:3244)
#157    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114)
#158    RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:161)
#159    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114)
#160    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2128)
#161    RenderView.hitTest (package:flutter/src/rendering/view.dart:172)
#162    RendererBinding.hitTest (package:flutter/src/rendering/binding.dart:364)
#163    GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:128)
#164    GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102)
#165    GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86)
#166    _rootRunUnary (dart:async/zone.dart:1136)
#167    _CustomZone.runUnary (dart:async/zone.dart:1029)
#168    _CustomZone.runUnaryGuarded (dart:async/zone.dart:931)
#169    _invoke1 (dart:ui/hooks.dart:263)
#170    _dispatchPointerDataPacket (dart:ui/hooks.dart:172)
`

**Comment by backcountrymountains** [comment]
So I changed the density of the phone from 240 to 200 and now portrait mode works fine.

However, setting the screen density of the phone to 200 makes the phone unstable, so I'd like to find a different solution.

I used the adb shell command:
`adb shell wm density 200`
